### ISSUE TITLE
beans & lombok

### ISSUE THREAD

**Issue by sysmat** [aldingithub/prpovaje#5]
- Zrna je včasih **boilerplate** koda(getters & setters), obstaja pa knjižnica lombok, ki nam olajša to
- [x] dodaj lombok in pretvori zrna, da uporabljajo lombok anotacije

**Comment by aldingithub** [comment]
Pozdravljeni, a je mišljeno zrna ali entitete, ker v zrnih ni getters in setters?

**Comment by sysmat** [comment]
zrna - beans, entitete, ...
